// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Dezert.Data;

#nullable disable

namespace ProjectDezert.Migrations
{
    [DbContext(typeof(Project_DezertContext))]
    partial class ProjectDezertContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_Dezert.Models.Photo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<byte[]>("Image")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.HasKey("Id");

                b.ToTable("Photo", (string)null);
            });

            modelBuilder.Entity("Project_Dezert.Models.Users", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Age")
                    .HasColumnType("int")
                    .HasColumnName("Age");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("City");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Country");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Login");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Name");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Password");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("PhoneNumber");

                b.Property<byte[]>("PhotoMain")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<int>("PhotosId")
                    .HasColumnType("int");

                b.Property<string>("Sername")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Sername");

                b.HasKey("Id");

                b.HasIndex("PhotosId");

                b.ToTable("Users", (string)null);
            });

            modelBuilder.Entity("Project_Dezert.Models.Users", b =>
            {
                b.HasOne("Project_Dezert.Models.Photo", "Photos")
                    .WithMany()
                    .HasForeignKey("PhotosId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Photos");
            });
#pragma warning restore 612, 618
        }
    }

}
