// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Dezert.Data;

#nullable disable

namespace ProjectDezert.Migrations
{
  
    partial class ProjectDezertContextModelSnapshot : ModelSnapshot
    {
       
    }
}
